//go:build !ignore_autogenerated

// Copyright 2026 Blink Labs Software
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccessPoint) DeepCopyInto(out *AccessPoint) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccessPoint.
func (in *AccessPoint) DeepCopy() *AccessPoint {
	if in == nil {
		return nil
	}
	out := new(AccessPoint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BlockProducerSpec) DeepCopyInto(out *BlockProducerSpec) {
	*out = *in
	out.Keys = in.Keys
	out.Rotation = in.Rotation
	out.HA = in.HA
	out.NodeToClient = in.NodeToClient
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BlockProducerSpec.
func (in *BlockProducerSpec) DeepCopy() *BlockProducerSpec {
	if in == nil {
		return nil
	}
	out := new(BlockProducerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ColdSignerSpec) DeepCopyInto(out *ColdSignerSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ColdSignerSpec.
func (in *ColdSignerSpec) DeepCopy() *ColdSignerSpec {
	if in == nil {
		return nil
	}
	out := new(ColdSignerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DingoNode) DeepCopyInto(out *DingoNode) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DingoNode.
func (in *DingoNode) DeepCopy() *DingoNode {
	if in == nil {
		return nil
	}
	out := new(DingoNode)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DingoNode) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DingoNodeList) DeepCopyInto(out *DingoNodeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DingoNode, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DingoNodeList.
func (in *DingoNodeList) DeepCopy() *DingoNodeList {
	if in == nil {
		return nil
	}
	out := new(DingoNodeList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DingoNodeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DingoNodeSpec) DeepCopyInto(out *DingoNodeSpec) {
	*out = *in
	if in.NetworkMagic != nil {
		in, out := &in.NetworkMagic, &out.NetworkMagic
		*out = new(int64)
		**out = **in
	}
	out.Image = in.Image
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	in.Persistence.DeepCopyInto(&out.Persistence)
	in.Resources.DeepCopyInto(&out.Resources)
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]v1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Affinity != nil {
		in, out := &in.Affinity, &out.Affinity
		*out = new(v1.Affinity)
		(*in).DeepCopyInto(*out)
	}
	if in.TerminationGracePeriodSeconds != nil {
		in, out := &in.TerminationGracePeriodSeconds, &out.TerminationGracePeriodSeconds
		*out = new(int64)
		**out = **in
	}
	if in.PodSecurityContext != nil {
		in, out := &in.PodSecurityContext, &out.PodSecurityContext
		*out = new(v1.PodSecurityContext)
		(*in).DeepCopyInto(*out)
	}
	if in.Environment != nil {
		in, out := &in.Environment, &out.Environment
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	in.Mithril.DeepCopyInto(&out.Mithril)
	in.Topology.DeepCopyInto(&out.Topology)
	if in.BlockProducer != nil {
		in, out := &in.BlockProducer, &out.BlockProducer
		*out = new(BlockProducerSpec)
		**out = **in
	}
	out.Metrics = in.Metrics
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DingoNodeSpec.
func (in *DingoNodeSpec) DeepCopy() *DingoNodeSpec {
	if in == nil {
		return nil
	}
	out := new(DingoNodeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DingoNodeStatus) DeepCopyInto(out *DingoNodeStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.KES = in.KES
	in.OpCert.DeepCopyInto(&out.OpCert)
	in.HA.DeepCopyInto(&out.HA)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DingoNodeStatus.
func (in *DingoNodeStatus) DeepCopy() *DingoNodeStatus {
	if in == nil {
		return nil
	}
	out := new(DingoNodeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalRelay) DeepCopyInto(out *ExternalRelay) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalRelay.
func (in *ExternalRelay) DeepCopy() *ExternalRelay {
	if in == nil {
		return nil
	}
	out := new(ExternalRelay)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HASpec) DeepCopyInto(out *HASpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HASpec.
func (in *HASpec) DeepCopy() *HASpec {
	if in == nil {
		return nil
	}
	out := new(HASpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HAStatus) DeepCopyInto(out *HAStatus) {
	*out = *in
	if in.StandbyPods != nil {
		in, out := &in.StandbyPods, &out.StandbyPods
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.LastPromotion != nil {
		in, out := &in.LastPromotion, &out.LastPromotion
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HAStatus.
func (in *HAStatus) DeepCopy() *HAStatus {
	if in == nil {
		return nil
	}
	out := new(HAStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageSpec) DeepCopyInto(out *ImageSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageSpec.
func (in *ImageSpec) DeepCopy() *ImageSpec {
	if in == nil {
		return nil
	}
	out := new(ImageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KESStatus) DeepCopyInto(out *KESStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KESStatus.
func (in *KESStatus) DeepCopy() *KESStatus {
	if in == nil {
		return nil
	}
	out := new(KESStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeysSpec) DeepCopyInto(out *KeysSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeysSpec.
func (in *KeysSpec) DeepCopy() *KeysSpec {
	if in == nil {
		return nil
	}
	out := new(KeysSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetricsSpec) DeepCopyInto(out *MetricsSpec) {
	*out = *in
	out.PodMonitor = in.PodMonitor
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricsSpec.
func (in *MetricsSpec) DeepCopy() *MetricsSpec {
	if in == nil {
		return nil
	}
	out := new(MetricsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MithrilSpec) DeepCopyInto(out *MithrilSpec) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.VerifyCertificates != nil {
		in, out := &in.VerifyCertificates, &out.VerifyCertificates
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MithrilSpec.
func (in *MithrilSpec) DeepCopy() *MithrilSpec {
	if in == nil {
		return nil
	}
	out := new(MithrilSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeToClientSpec) DeepCopyInto(out *NodeToClientSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeToClientSpec.
func (in *NodeToClientSpec) DeepCopy() *NodeToClientSpec {
	if in == nil {
		return nil
	}
	out := new(NodeToClientSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpCertStatus) DeepCopyInto(out *OpCertStatus) {
	*out = *in
	if in.OnChainCounterAt != nil {
		in, out := &in.OnChainCounterAt, &out.OnChainCounterAt
		*out = (*in).DeepCopy()
	}
	if in.LastRotated != nil {
		in, out := &in.LastRotated, &out.LastRotated
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpCertStatus.
func (in *OpCertStatus) DeepCopy() *OpCertStatus {
	if in == nil {
		return nil
	}
	out := new(OpCertStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PersistenceSpec) DeepCopyInto(out *PersistenceSpec) {
	*out = *in
	out.Size = in.Size.DeepCopy()
	if in.StorageClass != nil {
		in, out := &in.StorageClass, &out.StorageClass
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PersistenceSpec.
func (in *PersistenceSpec) DeepCopy() *PersistenceSpec {
	if in == nil {
		return nil
	}
	out := new(PersistenceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodMonitorSpec) DeepCopyInto(out *PodMonitorSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodMonitorSpec.
func (in *PodMonitorSpec) DeepCopy() *PodMonitorSpec {
	if in == nil {
		return nil
	}
	out := new(PodMonitorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RotationSpec) DeepCopyInto(out *RotationSpec) {
	*out = *in
	out.ColdSigner = in.ColdSigner
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RotationSpec.
func (in *RotationSpec) DeepCopy() *RotationSpec {
	if in == nil {
		return nil
	}
	out := new(RotationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TopologySpec) DeepCopyInto(out *TopologySpec) {
	*out = *in
	if in.AutoPeerRelays != nil {
		in, out := &in.AutoPeerRelays, &out.AutoPeerRelays
		*out = new(bool)
		**out = **in
	}
	if in.RelayRefs != nil {
		in, out := &in.RelayRefs, &out.RelayRefs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ExternalRelays != nil {
		in, out := &in.ExternalRelays, &out.ExternalRelays
		*out = make([]ExternalRelay, len(*in))
		copy(*out, *in)
	}
	if in.BootstrapPeers != nil {
		in, out := &in.BootstrapPeers, &out.BootstrapPeers
		*out = make([]AccessPoint, len(*in))
		copy(*out, *in)
	}
	if in.PublicRoots != nil {
		in, out := &in.PublicRoots, &out.PublicRoots
		*out = make([]AccessPoint, len(*in))
		copy(*out, *in)
	}
	if in.UseLedgerAfterSlot != nil {
		in, out := &in.UseLedgerAfterSlot, &out.UseLedgerAfterSlot
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TopologySpec.
func (in *TopologySpec) DeepCopy() *TopologySpec {
	if in == nil {
		return nil
	}
	out := new(TopologySpec)
	in.DeepCopyInto(out)
	return out
}
